-- ============================================================================
-- CRM seed — real Drive CRM history into Supabase (system of record).
-- GENERATED by scripts/build-crm-seed.ts from src/app/_data/dataset.ts.
-- Do not edit by hand; edit the dataset and regenerate.
-- Idempotent: profiles matched by name, deals/leads upserted on
-- (organization_id, external_id). Requires migrations 0000–0008.
-- Apply: supabase SQL editor, or psql "$DATABASE_URL" -f supabase/seeds/crm_seed.sql
-- ============================================================================

-- 1) Team identities -------------------------------------------------------
do $$
declare
  org constant uuid := '6a32be59-155d-4662-9058-3a74fb2b6872';
  a jsonb;
  v_id uuid;
begin
  for a in select * from jsonb_array_elements($staff$[
    {"name":"Shatha Al Manthari","email":"agent.shatha@alwalaaoman.com","staff_role":"senior_advisor","status":"active","segment":"diaspora","target":350000,"ramp_end":"","exempt":false,"drive":"https://drive.google.com/drive/folders/1-r9HPvaiH-LDbd3Rv6m_Sp_PiPDvaTJB","closed_docs":"https://drive.google.com/drive/folders/1vUhUiZygkAGtVwN_-10QP_tlOJs-Cey2","vouchers":"https://drive.google.com/drive/folders/1g7OSUcaOoq3SiOt2NuvRO05TD0Gy5fkN"},
    {"name":"Yousef","email":"agent.yousef@alwalaaoman.com","staff_role":"sales_manager","status":"former","segment":"na","target":0,"ramp_end":"","exempt":false,"drive":"https://drive.google.com/drive/folders/10Fr22TuuAXL6kj3Wa3vYPj_hA3dtVqXr","closed_docs":"https://drive.google.com/drive/folders/1qvuv5qbiRMZBXM_A_H3g4Pszo4kGenwN","vouchers":"https://drive.google.com/drive/folders/1J8ZM4_zrGDviuZdvD_2gubTmFOQnRlwZ"},
    {"name":"Alex Showran","email":"agent.alex@alwalaaoman.com","staff_role":"advisor","status":"active","segment":"resident","target":250000,"ramp_end":"","exempt":false,"drive":"https://drive.google.com/drive/folders/1BJMCIFLLcqqhv4IpaJxovcgiGHeIBlJU","closed_docs":"https://drive.google.com/drive/folders/1-XxmHUPyhzEGY5yfJ7t93H7-85NEkH_6","vouchers":"https://drive.google.com/drive/folders/1MoLzIKfHdJ54E-qyyxwKaGWoAsvzOuit"},
    {"name":"Pasha","email":"agent.pasha@alwalaaoman.com","staff_role":"advisor","status":"active","segment":"resident","target":250000,"ramp_end":"","exempt":false,"drive":"https://drive.google.com/drive/folders/1zBD-0lDQxZgwt0m74aNOgk16A8AyA6S9","closed_docs":"https://drive.google.com/drive/folders/1GlZNvJ15TVhicjlQAzSlueVzHoFxFo1a","vouchers":"https://drive.google.com/drive/folders/1_RXKortsifhp3GJRB5TCZMxD7mSjJMNJ"},
    {"name":"Wesam Zeno","email":"agent.wesam@alwalaaoman.com","staff_role":"advisor","status":"active","segment":"resident","target":250000,"ramp_end":"","exempt":false,"drive":"https://drive.google.com/drive/folders/18jh5WBpXifLf-5bxPdqRZQxHQW5FCDoB","closed_docs":"https://drive.google.com/drive/folders/1Hort5_HjU6jrhUkWMS7qvE6dvBsyPaqj","vouchers":"https://drive.google.com/drive/folders/14j4h7-9EU0Akbr9FGluwi377kmKEGv26"},
    {"name":"Khalid","email":"agent.khalid@alwalaaoman.com","staff_role":"advisor","status":"active","segment":"resident","target":120000,"ramp_end":"2026-09-01","exempt":false,"drive":"","closed_docs":"","vouchers":""},
    {"name":"Tariq","email":"agent.tariq@alwalaaoman.com","staff_role":"advisor","status":"active","segment":"na","target":0,"ramp_end":"","exempt":true,"drive":"https://drive.google.com/drive/folders/1ZxXvWfcyFh7vE-jLAJ83s-u-Ac9khtcz","closed_docs":"","vouchers":""},
    {"name":"Abeer Al Wardi","email":"agent.abeer@alwalaaoman.com","staff_role":"marketing_manager","status":"active","segment":"na","target":0,"ramp_end":"","exempt":false,"drive":"https://drive.google.com/drive/folders/1QlDo9hkF8WY2t8_xUHiZ2axf8v7K8P4C","closed_docs":"","vouchers":""}
  ]$staff$::jsonb) loop
    -- Reuse the existing profile when the person is already in the system.
    select p.id into v_id from profiles p
      where p.organization_id = org and lower(p.full_name) = lower(a->>'name')
      limit 1;
    if v_id is null then
      select u.id into v_id from auth.users u where lower(u.email) = lower(a->>'email');
    end if;
    if v_id is null then
      v_id := gen_random_uuid();
      insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at,
                              raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
      values ('00000000-0000-0000-0000-000000000000', v_id, 'authenticated', 'authenticated',
              a->>'email', now(),
              '{"provider":"email","providers":["email"]}'::jsonb,
              jsonb_build_object('name', a->>'name'), now(), now());
    end if;
    insert into profiles (id, organization_id, full_name, role)
    values (v_id, org, a->>'name', 'member')
    on conflict (id) do update set organization_id = excluded.organization_id,
                                   full_name = excluded.full_name;
    insert into staff_profiles (id, organization_id, role, status, segment,
                                monthly_target_omr, ramp_end_date, exempt_from_at_risk,
                                drive_folder_url, closed_docs_url, vouchers_url)
    values (v_id, org, (a->>'staff_role')::staff_role, (a->>'status')::staff_status,
            (a->>'segment')::agent_segment, (a->>'target')::numeric,
            nullif(a->>'ramp_end','')::date, (a->>'exempt')::boolean,
            nullif(a->>'drive',''), nullif(a->>'closed_docs',''), nullif(a->>'vouchers',''))
    on conflict (id) do update set
      role = excluded.role, status = excluded.status, segment = excluded.segment,
      monthly_target_omr = excluded.monthly_target_omr,
      ramp_end_date = excluded.ramp_end_date,
      exempt_from_at_risk = excluded.exempt_from_at_risk,
      drive_folder_url = excluded.drive_folder_url,
      closed_docs_url = excluded.closed_docs_url,
      vouchers_url = excluded.vouchers_url;
  end loop;
end $$;

-- 2) Remove hand-inserted demo rows ----------------------------------------
-- Every legitimate row (Zoho sync, Drive seed) carries an external_id; rows
-- without one were inserted by hand for demos and are not business truth.
delete from deals where organization_id = '6a32be59-155d-4662-9058-3a74fb2b6872' and external_id is null;
delete from leads where organization_id = '6a32be59-155d-4662-9058-3a74fb2b6872' and external_id is null;

-- 3) Deals (real Drive CRM history) ----------------------------------------
with src (external_id, agent_name, client_name, developer, project_name, unit_type,
          unit_number, value_omr, developer_pct, gross_omr, split_pct, payout_omr,
          source, developer_paid, agent_paid, is_reservation, closed_at, created_at,
          pv_reference) as (
  values
    ('drive:sh1', 'Shatha Al Manthari', 'Mohammad Edris Karim', 'Ahly Sabbour', 'Wadi Zaha', 'Studio', 'E26-D512', 43500, 0.035, 1522.5, 0.35, 532.88, 'ALWALAA', true, true, false, '2025-10-30T00:00:00Z', '2025-10-30T00:00:00Z', 'PV-2026-0003'),
    ('drive:sh2', 'Shatha Al Manthari', 'Christina & Andreas', 'Ahly Sabbour', 'Wadi Zaha', '2BD Penthouse', 'E26-D605', 139131.72, 0.035, 4869.61, 0.35, 1704.36, 'ALWALAA', true, true, false, '2026-01-05T00:00:00Z', '2026-01-05T00:00:00Z', 'PV-2026-0003'),
    ('drive:sh3', 'Shatha Al Manthari', 'Sukhwinder Singh', 'Ahly Sabbour', 'Wadi Zaha', 'Studio', 'E26-D402', 42750.48, 0.035, 1496.27, 0.5, 748.14, 'REFERRAL', true, true, false, '2026-01-07T00:00:00Z', '2026-01-07T00:00:00Z', null),
    ('drive:sh4', 'Shatha Al Manthari', 'Muhammad N. Momen', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B1-409', 62914.5, 0.04, 2516.58, 0.35, 880.8, 'ALWALAA', true, true, false, '2026-02-09T00:00:00Z', '2026-02-09T00:00:00Z', 'PV-2026-0007'),
    ('drive:sh5', 'Shatha Al Manthari', 'Mohammed Asaduzzaman', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B1-107', 50150, 0.04, 2006, 0.35, 702.1, 'ALWALAA', true, true, false, '2026-02-09T00:00:00Z', '2026-02-09T00:00:00Z', 'PV-2026-00011'),
    ('drive:sh6', 'Shatha Al Manthari', 'Mohamood Entezar', 'Sarooj Development', 'Sarooj Oasis', 'Penthouse 3BHK', 'B1-501', 173920, 0.04, 6956.8, 0.35, 2434.88, 'ALWALAA', true, true, false, '2026-02-25T00:00:00Z', '2026-02-25T00:00:00Z', 'PV-2026-0007'),
    ('drive:sh7', 'Shatha Al Manthari', 'Mohamood Entezar', 'Sarooj Development', 'Sarooj Oasis', '2BHK', 'B3-401', 92650, 0.04, 3706, 0.35, 1297.1, 'ALWALAA', true, true, false, '2026-02-25T00:00:00Z', '2026-02-25T00:00:00Z', 'PV-2026-0007'),
    ('drive:sh8', 'Shatha Al Manthari', 'Mhasood Entezar', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B3-409', 56100, 0.04, 2244, 0.35, 785.4, 'ALWALAA', true, true, false, '2026-02-25T00:00:00Z', '2026-02-25T00:00:00Z', null),
    ('drive:sh9', 'Shatha Al Manthari', 'Alan Ang', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B3-410', 56100, 0.04, 2244, 0.35, 785.4, 'ALWALAA', true, true, false, '2026-02-25T00:00:00Z', '2026-02-25T00:00:00Z', null),
    ('drive:sh10', 'Shatha Al Manthari', 'Nahida Karim', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B3-406', 54450, 0.04, 2178, 0.35, 762.3, 'ALWALAA', true, true, false, '2026-02-26T00:00:00Z', '2026-02-26T00:00:00Z', 'PV-2026-00011'),
    ('drive:sh11', 'Shatha Al Manthari', 'Nahida Karim', 'Ahly Sabbour', 'Wadi Zaha', '3BD Penthouse', 'E27-B604', 143715, 0.035, 5030.03, 0.35, 1760.51, 'ALWALAA', false, false, false, '2026-02-13T00:00:00Z', '2026-02-13T00:00:00Z', null),
    ('drive:sh12', 'Shatha Al Manthari', 'Helen Lauren & Peep Nork', 'Muriya', 'Olive Farms', '2BD', 'OL-204', 99000, 0.03, 2970, 0.35, 1039.5, 'ALWALAA', false, false, false, '2026-01-29T00:00:00Z', '2026-01-29T00:00:00Z', null),
    ('drive:sh13', 'Shatha Al Manthari', 'M. Muzahidul Islam', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B3-303', 52470, 0.04, 2098.8, 0.35, 734.58, 'ALWALAA', true, true, false, '2026-03-02T00:00:00Z', '2026-03-02T00:00:00Z', 'PV-2026-00011'),
    ('drive:sh14', 'Shatha Al Manthari', 'Volkmar Mannl', 'Ahly Sabbour', 'Wadi Zaha', '2BD Penthouse', 'E26-C602', 147000, 0.035, 5145, 0.35, 1800.75, 'ALWALAA', false, false, false, '2026-03-26T00:00:00Z', '2026-03-26T00:00:00Z', null),
    ('drive:sh15', 'Shatha Al Manthari', 'Mansoor Khan', 'Adante Realty', 'Yenaire', 'Retail', '96.GF.RT.01', 93348, 0.03, 2800.44, 0.35, 980.15, 'ALWALAA', false, false, false, '2026-05-02T00:00:00Z', '2026-05-02T00:00:00Z', null),
    ('drive:ax1', 'Alex Showran', 'Rasul Maideen', 'Adante Realty', 'Yenaire', '1BHK', '100.L1.06', 62502, 0.03, 1875.06, 0.25, 468.77, 'ALWALAA', true, true, false, '2025-12-18T00:00:00Z', '2025-12-18T00:00:00Z', null),
    ('drive:ax2', 'Alex Showran', 'Salahudin', 'Ahly Sabbour', 'Wadi Zaha', '2BHK', 'E26-C113', 77000, 0.035, 2695, 0.25, 641.67, 'ALWALAA', true, true, false, '2026-02-15T00:00:00Z', '2026-02-15T00:00:00Z', null),
    ('drive:ax3', 'Alex Showran', 'Zia Ul Haq', 'Ahly Sabbour', 'Wadi Zaha', '1BHK', 'E26-B302', 63200, 0.035, 2212, 0.25, 526.67, 'ALWALAA', true, true, false, '2026-02-04T00:00:00Z', '2026-02-04T00:00:00Z', 'PV-2026-0007'),
    ('drive:ax4', 'Alex Showran', 'Mohd. Ayaz', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B1-309', 61346.25, 0.04, 2453.85, 0.25, 613.46, 'ALWALAA', true, true, false, '2026-02-17T00:00:00Z', '2026-02-17T00:00:00Z', 'PV-2026-00011'),
    ('drive:ax5', 'Alex Showran', 'Dana', 'Ahly Sabbour', 'Wadi Zaha', 'Studio', 'E26-D508', 53833.33, 0.035, 1884.17, 0.25, 471.04, 'ALWALAA', true, true, false, '2026-04-16T00:00:00Z', '2026-04-16T00:00:00Z', null),
    ('drive:pa1', 'Pasha', 'Nadim ul Atik', 'Ahly Sabbour', 'Wadi Zaha', 'Apartment', 'B302', 78181.8, 0.035, 2736.36, 0.5, 1368.18, 'REFERRAL', false, false, false, '2026-04-22T00:00:00Z', '2026-04-22T00:00:00Z', null),
    ('drive:pa2', 'Pasha', 'Asif Ali Sheikh', 'Adante Realty', 'Yenaire', 'Studio', 'SD05-L7', 50104, 0.03, 1503.12, 0.25, 375.78, 'ALWALAA', false, false, false, '2026-05-02T00:00:00Z', '2026-05-02T00:00:00Z', null),
    ('drive:pa3', 'Pasha', 'Dr. Ashfaq Khan', 'Adante Realty', 'Yenaire', 'Apartment', 'L1-09', 80801, 0.03, 2424.03, 0.25, 606.01, 'ALWALAA', false, false, false, '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z', null),
    ('drive:pa4', 'Pasha', 'Mohammed Naji', 'Adante Realty', 'Yenaire', 'Studio', '101.L2.01', 63944, 0.03, 1918.32, 0.25, 479.58, 'ALWALAA', false, false, false, '2026-05-11T00:00:00Z', '2026-05-11T00:00:00Z', null),
    ('drive:pa5', 'Pasha', 'Ms Bano', 'Ahly Sabbour', 'Wadi Zaha', '1BHK', 'E22-102', 73400, 0.035, 2569, 0.35, 899.15, 'ALWALAA', false, false, true, null, '2026-05-15T00:00:00Z', null),
    ('drive:pa6', 'Pasha', 'Mr Nawaz', 'Ahly Sabbour', 'Wadi Zaha', 'Retail 98sqm', 'E27-B-R2', 93553, 0.035, 3274.36, 0.35, 1146.03, 'ALWALAA', false, false, true, null, '2026-05-15T00:00:00Z', null),
    ('drive:we1', 'Wesam Zeno', 'Ahmed Sahraoui', 'Al Abrar', 'Hay Al Wafaa', '2BHK', '59-D-203', 81950, 0.03, 2458.5, 0.25, 614.63, 'ALWALAA', true, true, false, '2026-01-29T00:00:00Z', '2026-01-29T00:00:00Z', 'PV-2026-0007'),
    ('drive:we2', 'Wesam Zeno', 'Alyaa Jasim Al Tameemi', 'Al Abrar', 'Hay Al Wafaa', 'Townhouse A', '10-22-4', 116495, 0.03, 3494.85, 0.25, 873.71, 'ALWALAA', true, true, false, '2026-01-20T00:00:00Z', '2026-01-20T00:00:00Z', 'PV-2026-0007'),
    ('drive:we3', 'Wesam Zeno', 'Alaa Alhakim', 'Sarooj Development', 'Sarooj Oasis', '1BHK', 'B2-002', 51415, 0.04, 2056.6, 0.25, 514.15, 'ALWALAA', true, true, false, '2026-02-05T00:00:00Z', '2026-02-05T00:00:00Z', 'PV-2026-00011'),
    ('drive:we4', 'Wesam Zeno', 'Lucia Semsakova', 'Ahly Sabbour', 'Wadi Zaha', 'Studio', 'E26-D302', 42250.48, 0.035, 1478.77, 0.25, 369.69, 'ALWALAA', true, true, false, '2026-01-28T00:00:00Z', '2026-01-28T00:00:00Z', 'PV-2026-0007')
)
insert into deals (organization_id, agent_id, client_name, project_id, value_omr,
                   developer_pct, gross_omr, split_pct, payout_omr, source,
                   developer_paid, agent_paid, is_reservation, closed_at, created_at,
                   external_id, developer, project_name, unit_type, unit_number,
                   pv_reference)
select '6a32be59-155d-4662-9058-3a74fb2b6872', prof.id, s.client_name, proj.id,
       s.value_omr::numeric, s.developer_pct::numeric, s.gross_omr::numeric,
       s.split_pct::numeric, s.payout_omr::numeric, s.source,
       s.developer_paid, s.agent_paid, s.is_reservation,
       s.closed_at::timestamptz, s.created_at::timestamptz, s.external_id,
       s.developer, s.project_name, s.unit_type, s.unit_number, s.pv_reference
from src s
join profiles prof
  on prof.organization_id = '6a32be59-155d-4662-9058-3a74fb2b6872' and lower(prof.full_name) = lower(s.agent_name)
left join lateral (
  select id from projects
  where organization_id = '6a32be59-155d-4662-9058-3a74fb2b6872' and lower(name) = lower(s.project_name)
  limit 1
) proj on true
on conflict (organization_id, external_id) where external_id is not null
do update set
  agent_id = excluded.agent_id, client_name = excluded.client_name,
  project_id = excluded.project_id, value_omr = excluded.value_omr,
  developer_pct = excluded.developer_pct, gross_omr = excluded.gross_omr,
  split_pct = excluded.split_pct, payout_omr = excluded.payout_omr,
  source = excluded.source, developer_paid = excluded.developer_paid,
  agent_paid = excluded.agent_paid, is_reservation = excluded.is_reservation,
  closed_at = excluded.closed_at, developer = excluded.developer,
  project_name = excluded.project_name, unit_type = excluded.unit_type,
  unit_number = excluded.unit_number, pv_reference = excluded.pv_reference;

-- 4) Leads (real Drive CRM pipeline) ---------------------------------------
with src (external_id, agent_name, title, name, phone_e164, email, country,
          nationality, budget_band, purpose, project_interest, source, raw_stage,
          stage, deal_status, registered_on, last_touch_at, notes) as (
  values
    ('drive:ld1', 'Alex Showran', 'Mr.', 'Jilal Malih', '+447958008313', null, 'United Kingdom', 'British', '75,000 – 100,000 OMR', 'Investment - Rental Income', 'Wadi Zaha', 'ALWALAA', 'Qualification meeting', 'engaged', 'In Progress', '2026-02-20', '2026-03-02T00:00:00Z', 'Couple + 2 children; SHC focus'),
    ('drive:ld2', 'Alex Showran', 'Dr.', 'Ali Imad Fadlallah', '+13136100000', null, 'United States', 'Lebanese', '150,000 – 200,000 OMR', 'Investment - Rental Income', 'Almouj Muscat', 'ALWALAA', 'Qualification meeting', 'engaged', 'In Progress', '2026-03-11', '2026-03-12T00:00:00Z', 'Planning to visit Oman'),
    ('drive:ld3', 'Alex Showran', 'Mr.', 'Sergei', '+971504325027', null, 'United Arab Emirates', 'Russian', '50,000 – 75,000 OMR', 'Secondary Home', 'Hay Al Wafaa', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-04-09', '2026-04-12T00:00:00Z', 'Software developer; needs time'),
    ('drive:ld4', 'Alex Showran', 'Mr.', 'Mortaza', '+447512277729', null, 'United Kingdom', 'Bangladeshi', '50,000 – 75,000 OMR', 'Investment - Rental Income', 'Wadi Zaha', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-04-12', '2026-04-30T00:00:00Z', 'Visiting 30 Apr with a friend'),
    ('drive:ld5', 'Alex Showran', 'Mrs.', 'Mariam', '+96566715055', null, 'Kuwait', 'Kuwaiti', '50,000 – 75,000 OMR', 'Primary Residence', 'Wadi Zaha', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-04-18', '2026-04-25T00:00:00Z', 'Waiting for the airport to open'),
    ('drive:ld6', 'Alex Showran', 'Mr.', 'Anas', '+9607942494', null, 'Maldives', 'Maldivian', '50,000 – 75,000 OMR', 'Investment - Rental Income', 'Wadi Zaha', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-05-12', null, 'Still exploring; needs another meeting'),
    ('drive:ld7', 'Alex Showran', 'Mr.', 'Harish', '+919535414557', null, 'India', 'Indian', '150,000 – 200,000 OMR', 'Investment - Rental Income', 'Sultan Haitham City', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-05-02', null, 'Townhouse; still deciding'),
    ('drive:ld8', 'Alex Showran', 'Mr.', 'Mohit', '+918745052020', null, 'India', 'Indian', '200,000 – 300,000 OMR', 'Primary Residence', 'Sultan Haitham City', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-05-03', null, 'Wants ready-to-move villa'),
    ('drive:ld9', 'Pasha', 'Mr.', 'Andreas', '+4917644473558', null, 'Germany', 'German', '50,000 – 75,000 OMR', 'Primary Residence', 'Sarooj Oasis', 'ALWALAA', 'Closing stage', 'negotiation', 'LOST', '2026-02-16', '2026-04-10T00:00:00Z', 'Needs more time to decide'),
    ('drive:ld10', 'Pasha', 'Mr.', 'Dabir', '+919820153254', 'dabir3006@gmail.com', 'India', 'Indian', 'Below 50,000 OMR', 'Primary Residence', 'Yenaire', 'ALWALAA', 'Qualification meeting', 'engaged', 'LOST', '2026-02-12', '2026-03-31T00:00:00Z', 'Dropped the plan for now'),
    ('drive:ld11', 'Pasha', 'Mr.', 'Ismail', '+96894676229', null, 'Oman', 'Egyptian', '50,000 – 75,000 OMR', 'Primary Residence', 'Sarooj Oasis', 'ALWALAA', 'Qualification meeting', 'engaged', 'In Progress', '2026-01-23', '2026-04-26T00:00:00Z', 'Awaiting sale of property in Türkiye'),
    ('drive:ld12', 'Pasha', 'Mrs.', 'Tahreem', '+48729672740', null, 'Poland', 'Pakistani', '75,000 – 100,000 OMR', 'Primary Residence', 'Wadi Zaha', 'ALWALAA', 'Qualification meeting', 'engaged', 'In Progress', '2026-02-26', '2026-04-26T00:00:00Z', 'Needs time due to conflict'),
    ('drive:ld13', 'Pasha', 'Mr.', 'Hamza', '+916307087381', 'itshamzafx1998@gmail.com', 'India', 'Indian', '500,000 – 1,000,000 OMR', 'Primary Residence', 'Muscat Bay', 'ALWALAA', 'Qualification meeting', 'engaged', 'LOST', '2026-02-23', '2026-03-01T00:00:00Z', 'Not a serious client'),
    ('drive:ld14', 'Pasha', 'Mrs.', 'Kamila', '+447933407813', 'kamilaqudsiashakeel@gmail.com', 'United Kingdom', 'British', '150,000 – 200,000 OMR', null, null, 'ALWALAA', 'Contacted', 'qualified', 'LOST', '2026-03-01', '2026-03-08T00:00:00Z', 'Not responding'),
    ('drive:ld15', 'Wesam Zeno', 'Mr.', 'Marcin', '+48502265192', 'santorinirestauracja@gmail.com', 'Poland', 'Polish', '50,000 – 75,000 OMR', 'Investment - Flip / Resale', 'Sarooj Oasis', 'ALWALAA', 'Closing stage', 'negotiation', 'LOST', '2025-12-26', '2026-04-28T00:00:00Z', 'Didn''t answer'),
    ('drive:ld16', 'Wesam Zeno', 'Mr.', 'Ibrahim AlKhulaifi', '+966562956156', null, 'Yemen', 'Yemeni', '50,000 – 75,000 OMR', 'Primary Residence', 'Sarooj Oasis', 'ALWALAA', 'Closing stage', 'reservation', 'CLOSED', '2025-10-23', '2026-04-11T00:00:00Z', 'Closed with Yousef'),
    ('drive:ld17', 'Wesam Zeno', 'Mr.', 'Matthias Weishaar', '+4917651135772', null, 'Germany', 'German', '50,000 – 75,000 OMR', 'Investment - Rental Income', 'Yenaire', 'ALWALAA', 'Closing stage', 'negotiation', 'LOST', '2025-11-11', '2026-04-17T00:00:00Z', 'Didn''t answer'),
    ('drive:ld18', 'Wesam Zeno', 'Mr.', 'Wicem', '+971503349661', null, 'United Arab Emirates', 'Indian', 'Below 50,000 OMR', 'Investment - Rental Income', 'Yenaire', 'ALWALAA', 'Closing stage', 'negotiation', 'LOST', '2025-11-11', '2026-04-17T00:00:00Z', 'Broker in Dubai'),
    ('drive:ld19', 'Shatha Al Manthari', 'Mr.', 'Brijesh', '+233558726', null, 'Ghana', 'Indian', '150,000 – 200,000 OMR', 'Primary Residence', 'Wadi Zaha', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-03-19', null, '3BHK; ready with booking fee; visiting May 1'),
    ('drive:ld20', 'Shatha Al Manthari', 'Mr.', 'Abrar Mohammed', '+97155407941', null, 'United Arab Emirates', null, '50,000 – 75,000 OMR', null, 'Jabal Sifah', 'ALWALAA', 'Qualification meeting', 'engaged', null, '2026-03-27', null, 'Muriya / Jabal Sifah interest'),
    ('drive:ld21', 'Shatha Al Manthari', 'Dr.', 'Elke Grundler', '+4915734206854', null, 'Germany', null, '150,000 – 200,000 OMR', null, null, 'ALWALAA', 'Contacted', 'qualified', null, '2026-02-22', '2026-04-03T00:00:00Z', 'Prefers to wait (GCC politics)'),
    ('drive:ld22', 'Pasha', 'Mr.', 'Yahia', '+447974176854', null, 'United Kingdom', null, null, null, null, 'ALWALAA', 'Contacted', 'qualified', null, '2026-03-05', null, 'Teacher; couple'),
    ('drive:ld23', 'Alex Showran', 'Mr.', 'Khozema', '+96550134483', null, 'Kuwait', 'Indian', '100,000 – 150,000 OMR', 'Primary Residence', 'Wadi Zaha', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-04-26', '2026-04-26T00:00:00Z', 'Townhouse; no proper response'),
    ('drive:ld24', 'Alex Showran', 'Mr.', 'Shoeb', '+15405564723', null, 'United States', 'Pakistani', 'Below 50,000 OMR', 'Primary Residence', 'Wadi Zaha', 'ALWALAA', 'Contacted', 'qualified', 'In Progress', '2026-05-10', null, 'Cannot make the down payment')
)
insert into leads (organization_id, assigned_agent_id, title, name, phone_e164,
                   email, country, nationality, budget_band, purpose,
                   project_interest, source, raw_stage, stage, deal_status,
                   registered_on, last_touch_at, notes, external_id,
                   interest_project_id)
select '6a32be59-155d-4662-9058-3a74fb2b6872', prof.id, s.title, s.name, s.phone_e164, s.email, s.country,
       s.nationality, s.budget_band, s.purpose, s.project_interest, s.source,
       s.raw_stage, s.stage::lead_stage, s.deal_status, s.registered_on::date,
       s.last_touch_at::timestamptz, s.notes, s.external_id, proj.id
from src s
left join profiles prof
  on prof.organization_id = '6a32be59-155d-4662-9058-3a74fb2b6872' and lower(prof.full_name) = lower(s.agent_name)
left join lateral (
  select id from projects
  where organization_id = '6a32be59-155d-4662-9058-3a74fb2b6872' and lower(name) = lower(s.project_interest)
  limit 1
) proj on true
on conflict (organization_id, external_id) where external_id is not null
do update set
  assigned_agent_id = excluded.assigned_agent_id, title = excluded.title,
  name = excluded.name, phone_e164 = excluded.phone_e164, email = excluded.email,
  country = excluded.country, nationality = excluded.nationality,
  budget_band = excluded.budget_band, purpose = excluded.purpose,
  project_interest = excluded.project_interest, source = excluded.source,
  raw_stage = excluded.raw_stage, stage = excluded.stage,
  deal_status = excluded.deal_status, registered_on = excluded.registered_on,
  last_touch_at = excluded.last_touch_at, notes = excluded.notes,
  interest_project_id = excluded.interest_project_id;
