// Generates supabase/seeds/crm_seed.sql from the baked CRM snapshot
// (src/app/_data/dataset.ts) — the consolidated REAL deal/lead history from
// the team's Drive CRM sheets. Run with:  npx tsx scripts/build-crm-seed.ts
//
// The seed makes Supabase the system of record for the dashboards:
//   1. Ensures a profile + staff_profiles row per team member (matched by
//      full_name; synthetic auth identity created only if missing — nobody
//      logs in with it in owner-only mode, it exists for the FK).
//   2. Deletes hand-inserted demo deals/leads (external_id IS NULL — every
//      legitimately synced or seeded row carries an external_id).
//   3. Upserts the real deals/leads keyed on (organization_id, external_id)
//      with external_id 'drive:<snapshot-id>', so re-running is a no-op.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { AGENTS, DEALS, LEADS, type AgentRecord } from "../src/app/_data/dataset";

const ORG = "6a32be59-155d-4662-9058-3a74fb2b6872";

const q = (v: string | null | undefined): string =>
  v == null ? "null" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined): string => (v == null ? "null" : String(v));

const STAFF_ROLE: Record<AgentRecord["role"], string> = {
  SENIOR: "senior_advisor",
  ADVISOR: "advisor",
  NEW: "advisor", // ramp_end_date marks the ramp window
  TRAINEE: "advisor", // exempt_from_at_risk marks the trainee
  HEAD_OF_SALES: "sales_manager",
  MARKETING: "marketing_manager",
  FINANCE: "finance_head",
  CEO: "ceo",
};

const agentName = new Map(AGENTS.map((a) => [a.id, a.name]));

const staffJson = AGENTS.map((a) =>
  JSON.stringify({
    name: a.name,
    email: `agent.${a.id}@alwalaaoman.com`,
    staff_role: STAFF_ROLE[a.role],
    status: a.status === "FORMER" ? "former" : "active",
    segment: a.segment.toLowerCase(),
    target: a.target,
    ramp_end: a.rampEndDate ?? "",
    exempt: a.exempt ?? false,
    drive: a.driveFolder ?? "",
    closed_docs: a.closedDocs ?? "",
    vouchers: a.vouchers ?? "",
  }),
);

// Reservations carry no closed_at; anchor their month via created_at mid-month.
const periodMidpoint = (period: string) => `${period}-15T00:00:00Z`;

const dealValues = DEALS.map((d) => {
  const name = agentName.get(d.agentId);
  if (!name) throw new Error(`Unknown agent ${d.agentId} on deal ${d.id}`);
  return `    (${q(`drive:${d.id}`)}, ${q(name)}, ${q(d.client)}, ${q(d.developer)}, ${q(d.project)}, ${q(d.unitType)}, ${q(d.unitNumber)}, ${n(d.value)}, ${n(d.devRatePct / 100)}, ${n(d.gross)}, ${n(d.splitPct / 100)}, ${n(d.payout)}, ${q(d.source)}, ${d.devPaid === "RECEIVED"}, ${d.agentPaid === "PAID"}, ${d.stage === "RESERVATION"}, ${d.closeDate ? q(`${d.closeDate}T00:00:00Z`) : "null"}, ${q(d.closeDate ? `${d.closeDate}T00:00:00Z` : periodMidpoint(d.period))}, ${q(d.pv ?? null)})`;
});

const leadValues = LEADS.map((l) => {
  const name = l.agentId ? agentName.get(l.agentId) ?? null : null;
  const phone = l.phoneRaw.replace(/[^+\d]/g, "");
  return `    (${q(`drive:${l.id}`)}, ${q(name)}, ${q(l.title)}, ${q(l.name)}, ${q(phone)}, ${q(l.email)}, ${q(l.country)}, ${q(l.nationality)}, ${q(l.budget)}, ${q(l.purpose)}, ${q(l.projectInterest)}, ${q(l.source)}, ${q(l.rawStage)}, ${q(l.stage.toLowerCase())}, ${q(l.dealStatus)}, ${q(l.registeredOn)}, ${l.lastFollowUp ? q(`${l.lastFollowUp}T00:00:00Z`) : "null"}, ${q(l.notes)})`;
});

const sql = `-- ============================================================================
-- CRM seed — real Drive CRM history into Supabase (system of record).
-- GENERATED by scripts/build-crm-seed.ts from src/app/_data/dataset.ts.
-- Do not edit by hand; edit the dataset and regenerate.
-- Idempotent: profiles matched by name, deals/leads upserted on
-- (organization_id, external_id). Requires migrations 0000–0008.
-- Apply: supabase SQL editor, or psql "$DATABASE_URL" -f supabase/seeds/crm_seed.sql
-- ============================================================================

-- 1) Team identities -------------------------------------------------------
do $$
declare
  org constant uuid := '${ORG}';
  a jsonb;
  v_id uuid;
begin
  for a in select * from jsonb_array_elements($staff$[
${staffJson.map((s) => `    ${s.replace(/\$/g, "$")}`).join(",\n")}
  ]$staff$::jsonb) loop
    -- Reuse the existing profile when the person is already in the system.
    select p.id into v_id from profiles p
      where p.organization_id = org and lower(p.full_name) = lower(a->>'name')
      limit 1;
    if v_id is null then
      select u.id into v_id from auth.users u where lower(u.email) = lower(a->>'email');
    end if;
    if v_id is null then
      v_id := gen_random_uuid();
      insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at,
                              raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
      values ('00000000-0000-0000-0000-000000000000', v_id, 'authenticated', 'authenticated',
              a->>'email', now(),
              '{"provider":"email","providers":["email"]}'::jsonb,
              jsonb_build_object('name', a->>'name'), now(), now());
    end if;
    insert into profiles (id, organization_id, full_name, role)
    values (v_id, org, a->>'name', 'member')
    on conflict (id) do update set organization_id = excluded.organization_id,
                                   full_name = excluded.full_name;
    insert into staff_profiles (id, organization_id, role, status, segment,
                                monthly_target_omr, ramp_end_date, exempt_from_at_risk,
                                drive_folder_url, closed_docs_url, vouchers_url)
    values (v_id, org, (a->>'staff_role')::staff_role, (a->>'status')::staff_status,
            (a->>'segment')::agent_segment, (a->>'target')::numeric,
            nullif(a->>'ramp_end','')::date, (a->>'exempt')::boolean,
            nullif(a->>'drive',''), nullif(a->>'closed_docs',''), nullif(a->>'vouchers',''))
    on conflict (id) do update set
      role = excluded.role, status = excluded.status, segment = excluded.segment,
      monthly_target_omr = excluded.monthly_target_omr,
      ramp_end_date = excluded.ramp_end_date,
      exempt_from_at_risk = excluded.exempt_from_at_risk,
      drive_folder_url = excluded.drive_folder_url,
      closed_docs_url = excluded.closed_docs_url,
      vouchers_url = excluded.vouchers_url;
  end loop;
end $$;

-- 2) Remove hand-inserted demo rows ----------------------------------------
-- Every legitimate row (Zoho sync, Drive seed) carries an external_id; rows
-- without one were inserted by hand for demos and are not business truth.
delete from deals where organization_id = '${ORG}' and external_id is null;
delete from leads where organization_id = '${ORG}' and external_id is null;

-- 3) Deals (real Drive CRM history) ----------------------------------------
with src (external_id, agent_name, client_name, developer, project_name, unit_type,
          unit_number, value_omr, developer_pct, gross_omr, split_pct, payout_omr,
          source, developer_paid, agent_paid, is_reservation, closed_at, created_at,
          pv_reference) as (
  values
${dealValues.join(",\n")}
)
insert into deals (organization_id, agent_id, client_name, project_id, value_omr,
                   developer_pct, gross_omr, split_pct, payout_omr, source,
                   developer_paid, agent_paid, is_reservation, closed_at, created_at,
                   external_id, developer, project_name, unit_type, unit_number,
                   pv_reference)
select '${ORG}', prof.id, s.client_name, proj.id,
       s.value_omr::numeric, s.developer_pct::numeric, s.gross_omr::numeric,
       s.split_pct::numeric, s.payout_omr::numeric, s.source,
       s.developer_paid, s.agent_paid, s.is_reservation,
       s.closed_at::timestamptz, s.created_at::timestamptz, s.external_id,
       s.developer, s.project_name, s.unit_type, s.unit_number, s.pv_reference
from src s
join profiles prof
  on prof.organization_id = '${ORG}' and lower(prof.full_name) = lower(s.agent_name)
left join lateral (
  select id from projects
  where organization_id = '${ORG}' and lower(name) = lower(s.project_name)
  limit 1
) proj on true
on conflict (organization_id, external_id) where external_id is not null
do update set
  agent_id = excluded.agent_id, client_name = excluded.client_name,
  project_id = excluded.project_id, value_omr = excluded.value_omr,
  developer_pct = excluded.developer_pct, gross_omr = excluded.gross_omr,
  split_pct = excluded.split_pct, payout_omr = excluded.payout_omr,
  source = excluded.source, developer_paid = excluded.developer_paid,
  agent_paid = excluded.agent_paid, is_reservation = excluded.is_reservation,
  closed_at = excluded.closed_at, developer = excluded.developer,
  project_name = excluded.project_name, unit_type = excluded.unit_type,
  unit_number = excluded.unit_number, pv_reference = excluded.pv_reference;

-- 4) Leads (real Drive CRM pipeline) ---------------------------------------
with src (external_id, agent_name, title, name, phone_e164, email, country,
          nationality, budget_band, purpose, project_interest, source, raw_stage,
          stage, deal_status, registered_on, last_touch_at, notes) as (
  values
${leadValues.join(",\n")}
)
insert into leads (organization_id, assigned_agent_id, title, name, phone_e164,
                   email, country, nationality, budget_band, purpose,
                   project_interest, source, raw_stage, stage, deal_status,
                   registered_on, last_touch_at, notes, external_id,
                   interest_project_id)
select '${ORG}', prof.id, s.title, s.name, s.phone_e164, s.email, s.country,
       s.nationality, s.budget_band, s.purpose, s.project_interest, s.source,
       s.raw_stage, s.stage::lead_stage, s.deal_status, s.registered_on::date,
       s.last_touch_at::timestamptz, s.notes, s.external_id, proj.id
from src s
left join profiles prof
  on prof.organization_id = '${ORG}' and lower(prof.full_name) = lower(s.agent_name)
left join lateral (
  select id from projects
  where organization_id = '${ORG}' and lower(name) = lower(s.project_interest)
  limit 1
) proj on true
on conflict (organization_id, external_id) where external_id is not null
do update set
  assigned_agent_id = excluded.assigned_agent_id, title = excluded.title,
  name = excluded.name, phone_e164 = excluded.phone_e164, email = excluded.email,
  country = excluded.country, nationality = excluded.nationality,
  budget_band = excluded.budget_band, purpose = excluded.purpose,
  project_interest = excluded.project_interest, source = excluded.source,
  raw_stage = excluded.raw_stage, stage = excluded.stage,
  deal_status = excluded.deal_status, registered_on = excluded.registered_on,
  last_touch_at = excluded.last_touch_at, notes = excluded.notes,
  interest_project_id = excluded.interest_project_id;
`;

const out = join(__dirname, "..", "supabase", "seeds", "crm_seed.sql");
writeFileSync(out, sql);
console.log(`Wrote ${out}: ${AGENTS.length} staff, ${DEALS.length} deals, ${LEADS.length} leads.`);
